package br.com.fitnesspro.workout.repository.auditable.health

import br.com.fitnesspro.jpa.IAuditableFitnessProRepository
import br.com.fitnesspro.models.workout.health.HealthConnectHeartRateSamples

interface IHealthConnectHeartRateSamplesRepository : IAuditableFitnessProRepository<HealthConnectHeartRateSamples>