package br.com.fitnesspro.repository.auditable.workout

import br.com.fitnesspro.models.workout.VideoExerciseExecution
import br.com.fitnesspro.repository.common.IAuditableFitnessProRepository

interface IVideoExerciseExecutionRepository: IAuditableFitnessProRepository<VideoExerciseExecution>