name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build
        run: ./mvnw clean package

      - name: Build Docker image
        run: docker build -t nikolasluiz123/fitnesspro-service .

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push nikolasluiz123/fitnesspro-service

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull nikolasluiz123/fitnesspro-service
            docker stop spring-app || true # Ignora erro se o container não estiver rodando
            docker rm spring-app || true # Ignora erro se o container não existir
            docker run -d -p 8080:8080 --name spring-app nikolasluiz123/fitnesspro-service